name: pcplus
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^5.0.1
  firebase_core: ^3.4.0
  firebase_auth: ^5.1.0
  firebase_messaging: ^15.0.1
  firebase_storage: ^12.0.1
  firebase_remote_config: ^5.0.1
  flutter_local_notifications: ^17.1.2
  fuzzy: ^0.5.1
  rxdart: ^0.27.7
  crypto: ^3.0.6
  momo_vn: ^2.0.2

  connectivity_plus: ^2.3.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  font_awesome_icon_class: ^0.0.6
  fl_chart: ^0.68.0
  gap: ^3.0.1
  get: ^4.6.6
  iconly: ^1.0.1
  pin_code_fields: ^8.0.1
  profanity_filter: ^2.0.0
  salomon_bottom_bar: ^3.3.2
  string_validator: ^1.0.2
  mailer: ^6.1.0
  pdf: ^3.10.8
  file_picker: ^8.1.6
  speech_to_text_google_dialog: ^0.0.6
  syncfusion_flutter_pdf: ^25.1.39
  open_file_plus: ^3.4.1+1
  path: ^1.9.0
  keyboard_dismisser: ^3.0.0
  image: ^4.1.7
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  speech_to_text: ^6.3.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.2.6
  image_picker: ^1.0.7

  async: ^2.11.0

  geolocator: ^12.0.0
  geocoding: ^3.0.0

  lazy_load_scrollview: ^1.3.0

  intl: ^0.19.0
  permission_handler: ^11.3.1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #  - assets/icons/
    - assets/images/
    - lib/sample/test_samples/
  #  - assets/fonts/
 # fonts:
  #  - family: Lexend
    #  fonts:
    #   - asset: assets/fonts/lexend/Lexend-Regular.ttf
   # - family: Montserrat
   #   fonts:
   #   - asset: assets/fonts/montserrat/Montserrat-Regular.ttf