// Đánh giá không thích
const List<String> feedbackDislike = [
  "Mình không thấy hài lòng lắm.",
  "Trải nghiệm này chưa được như kỳ vọng.",
  "Có nhiều điểm khiến mình thất vọng.",
  "Không phù hợp với nhu cầu của mình.",
  "Mình nghĩ cần cải thiện thêm nhiều.",
  "Không như mô tả ban đầu.",
  "Chất lượng chưa được tốt.",
  "Thật sự không ấn tượng.",
  "Không để lại cảm giác tốt.",
  "Khá thất vọng với kết quả nhận được.",
  "Cảm thấy lãng phí thời gian.",
  "Mình không có ý định quay lại.",
  "Không đáng với giá tiền.",
  "Mọi thứ khá tệ so với mong đợi.",
  "Mình không giới thiệu điều này cho người khác.",
  "Có nhiều điểm chưa hợp lý.",
  "Trải nghiệm không được suôn sẻ.",
  "Chưa đạt mức tối thiểu mong muốn.",
  "Làm mình cảm thấy không thoải mái.",
  "Mình cảm thấy tiếc vì đã thử.",
];

// Đánh giá trung lập / tạm ổn
const List<String> feedbackNeutral = [
  "Tạm ổn, không có gì đặc biệt.",
  "Mọi thứ đều ở mức chấp nhận được.",
  "Cũng được, không quá xuất sắc.",
  "Không quá tệ, nhưng cũng không quá tốt.",
  "Ổn nếu không đặt kỳ vọng cao.",
  "Mình thấy cũng ổn thôi.",
  "Có thể sử dụng nếu cần thiết.",
  "Trải nghiệm ở mức trung bình.",
  "Không có gì để phàn nàn nhiều.",
  "Khá bình thường, không có điểm nhấn.",
  "Không đặc sắc, nhưng chấp nhận được.",
  "Có thể cân nhắc nếu không còn lựa chọn khác.",
  "Mình không quá ấn tượng, nhưng cũng không thất vọng.",
  "Mức độ hài lòng ở mức trung bình.",
  "Vẫn có thể dùng được.",
  "Không quá nổi bật, nhưng không tệ.",
  "Mọi thứ đều ổn, không hơn không kém.",
  "Hợp lý trong một số trường hợp.",
  "Không làm mình khó chịu, nhưng cũng không làm mình vui.",
  "Cũng đáng thử một lần.",
];

// Đánh giá rất thích
const List<String> feedbackLike = [
  "Mình thật sự rất hài lòng!",
  "Trải nghiệm vượt xa mong đợi!",
  "Rất tuyệt vời, không có gì để chê.",
  "Hoàn toàn ấn tượng!",
  "Mình sẽ quay lại nhiều lần nữa.",
  "Rất đáng đồng tiền bát gạo.",
  "Một lựa chọn không thể tốt hơn.",
  "Mình cực kỳ khuyến khích mọi người thử.",
  "Quá tuyệt, mình không ngờ luôn!",
  "Đây là một trong những trải nghiệm tốt nhất của mình.",
  "Mọi thứ đều hoàn hảo.",
  "Mình rất thích và sẽ giới thiệu cho bạn bè.",
  "Chất lượng vượt trội!",
  "Mình hoàn toàn bị thuyết phục.",
  "Rất phù hợp với nhu cầu của mình.",
  "Một trải nghiệm đáng nhớ.",
  "Mình không thể đòi hỏi gì hơn.",
  "Cảm giác rất vui và hài lòng.",
  "Làm mình muốn trải nghiệm thêm lần nữa.",
  "Tất cả đều trên cả mong đợi.",
];
