// ignore_for_file: constant_identifier_names

const List<String> LOCATIONS = [
  "Hà Nội",
  "TP. Hồ Chí Minh",
  "Hải Phòng",
  "Đà Nẵng",
  "Cần Thơ",
  "Huế",
  "Điện Biên",
  "Lai Châu",
  "Lào Cai",
  "Cao Bằng",
  "Lạng Sơn",
  "Tuyên Quang",
  "Thái Nguyên",
  "Sơn La",
  "Phú Thọ",
  "Bắc Ninh",
  "Quảng Ninh",
  "Hưng Yên",
  "Ninh Bình",
  "Thanh Hóa",
  "Nghệ An",
  "Hà Tĩnh",
  "Quảng Trị",
  "Quảng Ngãi",
  "Gia Lai",
  "Đắk Lắk",
  "Khánh Hòa",
  "Lâm Đồng",
  "Tây Ninh",
  "Đồng Nai",
  "Đồng Tháp",
  "An Giang",
  "Vĩnh Long",
  "Cà Mau",
];
